modLoader="javafml"
loaderVersion="[47,)"
license=" CC-BY-NC-4.0 + https://pastebin.com/47smwufD"

[[mods]]
modId="palamod"
version="1.20.026.2"
displayName="Palamod renew"
updateJSONURL="https://github.com/cbaie9/ng_wpckiller/raw/main/update.json"
displayURL="Paladium team :  https://paladium-pvp.fr , Discord :  https://discord.com/invite/dVvNDrQENA"
logoFile="logo.png"
credits="Developed by guys who want exit warzone without being killed ---  NOT affiliated with mojang, microsoft or Paladium games "
authors="cb9, FufuBS1 ( + Paladium Games for the original mod)"
description="Un univers alternatif où la v5 à bien changé de version  -- A mod who remake Palamod from French server Paladium from scratch ( and some texture )"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.palamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.palamod]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration